#include <avr/io.h>
#include <util/delay.h>
#include <avr/interrupt.h>

#define clk_x PB3
#define dir_x PB4
#define en_x PB5
#define clk_y PC3
#define dir_y PC4
#define en_y PC5
#define SOL PC0



void pwm_motor_x() {
	DDRB |= (1 << clk_x) | (1 << dir_x) | (1 << en_x);

	TCCR2A |= (1 << COM2A0) | (1 << WGM21) | (1 << WGM20);
	TCCR2B |= (1 << WGM22);
	TCCR2B |= (1 << CS21);

	OCR2A = 200;
}

void motor_x_velocidad(uint8_t velocidad) {
	OCR2A = velocidad;
}

void pwm_motor_y() {
	DDRC |= (1 << clk_y) | (1 << dir_y) | (1 << en_y) | (1 << SOL);

	TCCR1A = 0;
	TCCR1B |= (1 << WGM12);
	TCCR1B |= (1 << CS11);

	OCR1A = 200;

	TIMSK1 |= (1 << OCIE1A);
	
}



void motor_y_velocidad(uint8_t velocidad) {
	OCR1A = velocidad;
	sei();
}

ISR(TIMER1_COMPA_vect) {
	PORTC ^= (1 << clk_y);
}

void mover_abajo() {
	PORTB |= (1 << dir_y) | (1 << en_y);
}

void mover_arriba() {
	PORTB |= (1 << en_y);
	PORTB &= ~(1 << dir_y);
}

void detener() {
	PORTB &= ~((1 << en_x) | (1 << dir_x));
	PORTC &= ~((1 << en_y) | (1 << dir_y));
	_delay_ms(100);
}

void mover_izquierda() {
	PORTC |= (1 << en_x);
	PORTC &= ~(1 << dir_x);
}

void mover_derecha() {
	PORTC |= (1 << dir_x) | (1 << en_x);
}

void subir_lapiz() {
	PORTC |= (1 << SOL);
}

void bajar_lapiz() {
	PORTC &= ~(1 << SOL);
}

void cruz() {
	bajar_lapiz();
	mover_derecha();
	_delay_ms(1000);
	mover_izquierda();
	_delay_ms(500);
	detener();
	mover_arriba();
	_delay_ms(500);
	mover_abajo();
	_delay_ms(1000);
	detener();
	subir_lapiz();
}

void triangulo() {
	bajar_lapiz();
	mover_derecha();
	_delay_ms(1000);
	mover_izquierda();
	mover_arriba();
	_delay_ms(500);
	mover_abajo();
	_delay_ms(500);
	detener();
	subir_lapiz();
	
}

void circulo() {
	bajar_lapiz();
	mover_izquierda();
	_delay_ms(250);
	detener();
	for (int i = 0;i<5;i++) {
		mover_izquierda();
		_delay_ms(50);
		detener();
		mover_abajo();
		_delay_ms(30);
		detener();
	}
	for (int i = 0;i<5;i++) {
		mover_izquierda();
		_delay_ms(25);
		detener();
		mover_abajo();
		_delay_ms(30);
		detener();
	}
	for (int i = 0;i<5;i++) {
		mover_izquierda();
		_delay_ms(25);
		detener();
		mover_abajo();
		_delay_ms(60);
		detener();
	}
	mover_abajo();
	_delay_ms(200);
	detener();
	for (int i = 0;i<5;i++) {
		mover_abajo();
		_delay_ms(60);
		detener();
		mover_derecha();
		_delay_ms(25);
		detener();
	}
	for (int i = 0;i<5;i++) {
		mover_abajo();
		_delay_ms(30);
		detener();
		mover_derecha();
		_delay_ms(25);
		detener();
	}
	for (int i = 0;i<5;i++) {
		mover_abajo();
		_delay_ms(30);
		detener();
		mover_derecha();
		_delay_ms(50);
		detener();
	}
	mover_derecha();
	_delay_ms(200);
	detener();
	for (int i = 0;i<5;i++) {
		mover_arriba();
		_delay_ms(30);
		detener();
		mover_derecha();
		_delay_ms(50);
		detener();
	}
	for (int i = 0;i<5;i++) {
		mover_arriba();
		_delay_ms(30);
		detener();
		mover_derecha();
		_delay_ms(25);
		detener();
	}
	for (int i = 0;i<5;i++) {
		mover_arriba();
		_delay_ms(60);
		detener();
		mover_derecha();
		_delay_ms(25);
		detener();
	}
	mover_arriba();
	_delay_ms(200);
	detener();
	for (int i = 0;i<5;i++) {
		mover_izquierda();
		_delay_ms(25);
		detener();
		mover_arriba();
		_delay_ms(60);
		detener();
	}
	for (int i = 0;i<5;i++) {
		mover_arriba();
		_delay_ms(30);
		detener();
		mover_izquierda();
		_delay_ms(25);
		detener();
	}
	for (int i = 0;i<5;i++) {
		mover_izquierda();
		_delay_ms(50);
		detener();
		mover_arriba();
		_delay_ms(30);
		detener();
	}
	subir_lapiz();
}



void rana() {
	bajar_lapiz();
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(250);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(250);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_derecha();//1
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();//2
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//3
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//4
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//5
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();//6
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_derecha();//7
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();//8
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//9
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();//10
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//11
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//12
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//13
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//14
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//15
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//16
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//17
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//18
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//19
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_derecha();//1
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//2
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//3
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();//4
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_derecha();//5
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();//6
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(300);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(600);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(500);
	detener();
	_delay_ms(200);

	mover_izquierda();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(350);
	detener();
	_delay_ms(200);
	
	mover_abajo();
	_delay_ms(350);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	//pz delantera
	mover_izquierda();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(400);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	//pzdr1
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(400);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);	
	mover_derecha();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(500);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(350);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(150);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(150);
	detener();
	_delay_ms(100);
	
	mover_derecha();
	_delay_ms(150);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(150);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	
	mover_izquierda();//1
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//2
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//3
	_delay_ms(100);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//4
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//5
	_delay_ms(100);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//6
	_delay_ms(100);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//7
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//8
	_delay_ms(100);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//9
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//10
	_delay_ms(100);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//11
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//12
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//13
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//14
	_delay_ms(100);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();//15
	_delay_ms(150);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	subir_lapiz();
	_delay_ms(100);
	mover_izquierda();
	_delay_ms(300);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	
	bajar_lapiz();
	_delay_ms(100);
	mover_izquierda();
	_delay_ms(150);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(150);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(100);
	//
	detener();
	subir_lapiz();
}
	
void flor() {
	bajar_lapiz();
	// 1er petalo
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_abajo();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	//
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	// 2do petalo
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	//
	mover_derecha();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	//3er petalo
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	//
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	// 4to petalo
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);	
	
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_izquierda();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	//
	mover_abajo();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	// 5to petalo
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_arriba();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	//
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	// 6to Petalo
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	//
	mover_izquierda();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	// 7mo petalo
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	
	mover_derecha();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	//
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(150);
	detener();
	_delay_ms(200);
	// 8vo petalo
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_arriba();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(200);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	detener();
	_delay_ms(200);
	mover_abajo();
	_delay_ms(50);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(100);
	//
	// /
	detener();
	subir_lapiz();
}

int main(void) {
	subir_lapiz();
	pwm_motor_x();
	pwm_motor_y();
	motor_x_velocidad(200);
	motor_y_velocidad(200);
	cruz();
	mover_abajo();
	_delay_ms(2000);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(200);
	triangulo();
	mover_abajo();
	_delay_ms(2000);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(200);
	circulo();
	mover_abajo();
	_delay_ms(2000);
	detener();
	_delay_ms(200);
	mover_derecha();
	_delay_ms(200);
	flor();
	mover_arriba();
	_delay_ms(2000);
	detener();
	_delay_ms(200);
	mover_izquierda();
	_delay_ms(200);
	motor_x_velocidad(128);
	motor_y_velocidad(128);
	rana();

	while (1) {
		motor_x_velocidad(200);
		motor_y_velocidad(200);
		
	}
	
	return 0;
}